version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "30300:30300"
      - "20200:20200"
    volumes:
      - ./config.json:/app/config.json
      - ./solidity:/app/solidity
    command: ["python", "-m", "src.server.run"]